### ISSUE TITLE
Laggy at FPS above 120

### ISSUE THREAD

**Issue by Bladeshadow3822** [star-studios-official/FNF-Shattered-Engine-0.6.3#1]
### Describe your bug here.

Version: 0.0.1 pre-release
Issue: Any FPS above 120 lags the game until you load a song
OS: Linux (Untested on Windows)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by natesway** [comment]
Fixed
